---
- name: Atualizar Kernel e reinstalar Kaspersky
  hosts: all
  become: yes

  vars:
    script_local: "./script.sh"
    script_remoto: "/tmp/script.sh"

  tasks:
    - name: Copiar script para o servidor remoto
      copy:
        src: "{{ script_local }}"
        dest: "{{ script_remoto }}"
        mode: '0755'

    - name: Executar script no servidor remoto
      command: bash {{ script_remoto }}
