---
- name: Clonar repositório, instalar .deb e executar script
  hosts: all
  become: yes
  vars:
    repo_git: "https://github.com/anhenrique/ansible.git"
    pasta_destino: "/tmp/"
    nome_arquivo_deb: "klnagent64_13.2.2-1263_amd64.deb"
    script_sh: "script.sh"

  tasks:

    - name: Garantir que git está instalado
      apt:
        name: git
        state: present
        update_cache: yes

    - name: Clonar repositório Git
      git:
        repo: "{{ repo_git }}"
        dest: "{{ pasta_destino }}"
        version: HEAD
        force: yes

    - name: Instalar pacote .deb do repositório
      apt:
        deb: "{{ pasta_destino }}/{{ nome_arquivo_deb }}"
        state: present

    - name: Executar script .sh do repositório
      command: "bash {{ pasta_destino }}/{{ script_sh }}"
