---
- name: Clonar reposit칩rio, instalar .deb e executar script
  hosts: all
  become: yes
  vars:
    repo_git: "https://github.com/anhenrique/ansible.git"
    pasta_destino: "/root/ansible"
    script_sh: "script.sh"

  tasks:

    - name: Garantir que git est치 instalado
      apt:
        name: git
        state: present
        update_cache: yes

    - name: Clonar reposit칩rio Git
      git:
        repo: "{{ repo_git }}"
        dest: "{{ pasta_destino }}"
        version: HEAD
        force: yes

    - name: Executar script .sh do reposit칩rio
      command: "bash {{ pasta_destino }}/{{ script_sh }}"
